### ISSUE TITLE
There is an error when choosing "consider homology"

### ISSUE THREAD

**Issue by shlomtzion** [MayroseLab/CRISPys#23]
This is the error file to an example:

/: No such file or directory.
Traceback (most recent call last):
  File "/groups/itay_mayrose/galhyams/CrispysV1.6_2505/call_MULTICRISPR_Wrapper.py", line 220, in <module>
    call_using_CasSites_server_new(*sys.argv[1:])
  File "/groups/itay_mayrose/galhyams/CrispysV1.6_2505/call_MULTICRISPR_Wrapper.py", line 81, in call_using_CasSites_server_new
    res = wrapperE.call_it_all(genesList, genesNames, sg_genes_dict, genes_sg_dict, Omega, protodist_outfile, path, df_targets, internal_node_candidates, cfd_dict, PS_number)
  File "/groups/itay_mayrose/galhyams/CrispysV1.6_2505/WrapperVers3E.py", line 77, in call_it_all
    upgmaTree, distance_matrix = original_wrapper.return_UPGMA(genesList, genesNames, protodist_outfile, pylip_temps_path) #to uncomment when using wighted
  File "/groups/itay_mayrose/galhyams/CrispysV1.6_2505/WrapperVers3.py", line 327, in return_UPGMA
    mafft_and_phylip.runIt(new_names_list, seq_list,protdist_outfile, pylip_temps_path) #to uncomment when really ranning the tool on the server
  File "/groups/itay_mayrose/galhyams/CrispysV1.6_2505/mafft_and_phylip.py", line 86, in runIt
    call_mafft_0(fasta_outfile, aligned_file)
  File "/groups/itay_mayrose/galhyams/CrispysV1.6_2505/mafft_and_phylip.py", line 26, in call_mafft_0
    stdout, stderr = mafft_cline()
  File "/share/apps/python/anaconda3-4.0.0/lib/python3.5/site-packages/Bio/Application/__init__.py", line 516, in __call__
    stdout_str, stderr_str)
Bio.Application.ApplicationError: Non-zero return code 1 from 'mafft /bioseq/data/results/multicrispr/1515402357/fasta_outfile.fa', message 'v0.000 != v7.305b (2016/Aug/16)'

**Comment by HyamsG** [comment]
It is not a bug in the code. I havan't changed anything related to this. the only thing I've changed the code since starting the revision is presenting more positions in the output file, which happens in a way later stage.
I've checked this bug looks like the default version of 'mafft' on the server was changed by someone - to a non-working version (try just writing mafft in the shell and you'll see this yourself)

anyhow, apparently, Anat had the same problem, and she helped me fix it, so now it is fixed

**Comment by shlomtzion** [comment]
It still shows me this error

**Comment by shlomtzion** [comment]
For example 1515924703

**Comment by HyamsG** [comment]
From my user it worked. try add this call before calling to crispys: 'module load mafft/mafft7149'
from python, it will be like this:
os.system('module load mafft/mafft7149')
in addition, I've added the formation o the 'greedy set cover' file. it is called greedy_cover.p.
this file is available only at the version at /groups/itay_mayrose/galhyams/CRISPys_revision_25_12.

besides fixing bugs in the old version, all of my changes are done there.

thanks
Gal
